"""empty message

Revision ID: 0e5d7f5a16cb
Revises: cf997ad34721
Create Date: 2020-06-07 20:10:18.278148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5d7f5a16cb'
down_revision = 'cf997ad34721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kubecontainers', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kubecontainers', 'name')
    # ### end Alembic commands ###
