"""empty message

Revision ID: 15034d92da55
Revises: 7c9341ea537b
Create Date: 2020-08-02 21:28:23.781443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15034d92da55'
down_revision = '7c9341ea537b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_constraint('service_ports_kube_container_id_fkey', 'service_ports', type_='foreignkey')
    op.drop_column('service_ports', 'kube_container_id')
    op.drop_table('kubecontainers')
    op.drop_table('containers')
    op.add_column('deployments', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.add_column('deployments', sa.Column('workspace_port_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deployments', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'deployments', 'service_ports', ['workspace_port_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_ports', sa.Column('kube_container_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('service_ports_kube_container_id_fkey', 'service_ports', 'kubecontainers', ['kube_container_id'], ['id'])
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_column('deployments', 'workspace_port_id')
    op.drop_column('deployments', 'workspace_id')
    op.create_table('kubecontainers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('container_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], name='kubecontainers_container_id_fkey'),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name='kubecontainers_deployment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='kubecontainers_pkey')
    )
    op.create_table('containers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='containers_pkey'),
    sa.UniqueConstraint('name', name='containers_name_key')
    )
    op.drop_table('workspaces')
    # ### end Alembic commands ###
