"""empty message

Revision ID: 1bcf536668c9
Revises: 0e5d7f5a16cb
Create Date: 2020-06-07 20:28:41.417133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bcf536668c9'
down_revision = '0e5d7f5a16cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('pod', sa.String(length=64), nullable=True))
    op.drop_column('kubecontainers', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kubecontainers', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('deployments', 'pod')
    # ### end Alembic commands ###
