"""empty message

Revision ID: 3377bcf8cb33
Revises: 15034d92da55
Create Date: 2020-08-03 12:01:52.317796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3377bcf8cb33'
down_revision = '15034d92da55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('language', sa.String(length=30), nullable=False))
    op.drop_constraint('workspaces_name_key', 'workspaces', type_='unique')
    op.create_unique_constraint(None, 'workspaces', ['language'])
    op.drop_column('workspaces', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workspaces', type_='unique')
    op.create_unique_constraint('workspaces_name_key', 'workspaces', ['name'])
    op.drop_column('workspaces', 'language')
    # ### end Alembic commands ###
