"""empty message

Revision ID: 5398c0652113
Revises: d8749db33981
Create Date: 2020-06-01 12:21:06.925217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5398c0652113'
down_revision = 'd8749db33981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kubecontainers', 'container_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kubecontainers', 'container_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
