"""empty message

Revision ID: 5f788e6c0c47
Revises: 3377bcf8cb33
Create Date: 2020-08-03 12:03:25.508818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f788e6c0c47'
down_revision = '3377bcf8cb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('name', sa.String(length=30), nullable=False))
    op.drop_constraint('workspaces_language_key', 'workspaces', type_='unique')
    op.create_unique_constraint(None, 'workspaces', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='unique')
    op.create_unique_constraint('workspaces_language_key', 'workspaces', ['language'])
    op.drop_column('workspaces', 'name')
    # ### end Alembic commands ###
