"""empty message

Revision ID: 6c6191deab0f
Revises: fa10536794d0
Create Date: 2020-09-25 19:07:16.607011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6191deab0f'
down_revision = 'fa10536794d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('turn_interval', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'turn_interval')
    # ### end Alembic commands ###
