"""empty message

Revision ID: 72b684813fd7
Revises: e7d80a389411
Create Date: 2020-06-09 20:04:47.221117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72b684813fd7'
down_revision = 'e7d80a389411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kubecontainers', sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kubecontainers', 'options')
    # ### end Alembic commands ###
