"""empty message

Revision ID: 78d101e21f05
Revises: 5f788e6c0c47
Create Date: 2020-08-03 13:43:45.687949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d101e21f05'
down_revision = '5f788e6c0c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('display_name', sa.String(length=30), nullable=False))
    op.drop_column('workspaces', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('language', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('workspaces', 'display_name')
    # ### end Alembic commands ###
