"""empty message

Revision ID: 7c9341ea537b
Revises: bbc8433264b5
Create Date: 2020-06-20 19:40:20.321339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9341ea537b'
down_revision = 'bbc8433264b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('players_game_id_fkey', 'players', type_='foreignkey')
    op.drop_column('players', 'game_id')
    op.drop_table('games')
    op.drop_table('gametypes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('players_game_id_fkey', 'players', 'games', ['game_id'], ['id'])
    op.create_table('gametypes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('gametypes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='gametypes_pkey'),
    sa.UniqueConstraint('name', name='gametypes_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('running', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['gametypes.id'], name='games_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='games_pkey')
    )
    # ### end Alembic commands ###
