"""empty message

Revision ID: 8451b27fa1b6
Revises: 2749aed388d5
Create Date: 2020-04-20 17:58:52.833588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8451b27fa1b6'
down_revision = '2749aed388d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
