"""empty message

Revision ID: b4a9c0be3623
Revises: 1bcf536668c9
Create Date: 2020-06-08 20:45:44.107453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a9c0be3623'
down_revision = '1bcf536668c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_ports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('kube_container_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kube_container_id'], ['kubecontainers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_ports')
    # ### end Alembic commands ###
