"""empty message

Revision ID: b4d5e9d7ba98
Revises: 78d101e21f05
Create Date: 2020-08-03 20:10:03.687462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d5e9d7ba98'
down_revision = '78d101e21f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_ports', sa.Column('url_params', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'workspaces', ['display_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='unique')
    op.drop_column('service_ports', 'url_params')
    # ### end Alembic commands ###
