"""empty message

Revision ID: cf997ad34721
Revises: ce204a16eddd
Create Date: 2020-06-07 19:36:19.663714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf997ad34721'
down_revision = 'ce204a16eddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('status', sa.String(length=32), server_default='Stopped', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'status')
    # ### end Alembic commands ###
