"""empty message

Revision ID: d2c3ac4ee8c8
Revises: 9db45a5eaea2
Create Date: 2020-05-15 12:50:39.528076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c3ac4ee8c8'
down_revision = '9db45a5eaea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('containers_image_key', 'containers', type_='unique')
    op.drop_column('containers', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('image', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('containers_image_key', 'containers', ['image'])
    # ### end Alembic commands ###
