"""empty message

Revision ID: d868746b92a1
Revises: 9224cd4fb624
Create Date: 2020-04-24 15:18:32.525119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd868746b92a1'
down_revision = '9224cd4fb624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deployments', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_column('deployments', 'creator_id')
    # ### end Alembic commands ###
