"""empty message

Revision ID: d8749db33981
Revises: f4200467357c
Create Date: 2020-06-01 12:13:14.594589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8749db33981'
down_revision = 'f4200467357c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kubecontainers', 'deployment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kubecontainers', 'deployment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
