"""empty message

Revision ID: ef81eedd1764
Revises: 34aaace1c377
Create Date: 2020-06-02 20:39:31.367555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef81eedd1764'
down_revision = '34aaace1c377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testmodel', sa.Column('name2', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testmodel', 'name2')
    # ### end Alembic commands ###
