"""empty message

Revision ID: f4200467357c
Revises: d2c3ac4ee8c8
Create Date: 2020-05-18 14:23:12.846201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4200467357c'
down_revision = 'd2c3ac4ee8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kubecontainers', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kubecontainers', 'username')
    # ### end Alembic commands ###
