"""empty message

Revision ID: fa10536794d0
Revises: 3dd19d46ac6d
Create Date: 2020-09-25 18:54:22.940075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa10536794d0'
down_revision = '3dd19d46ac6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('field_size', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('max_players', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('num_bots', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('num_food', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'num_food')
    op.drop_column('games', 'num_bots')
    op.drop_column('games', 'max_players')
    op.drop_column('games', 'field_size')
    # ### end Alembic commands ###
